org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.21.11
# NOTE: Yarn will NOT be updated past 1.21.11 (last obfuscated MC version).
# Fabric recommends migrating to Mojang Mappings for future MC versions.
# See: https://docs.fabricmc.net/develop/migrating-mappings/
yarn_mappings=1.21.11+build.4
loader_version=0.18.5
fabric_version=0.141.4+1.21.11

mod_version=2.5.0
maven_group=com.jumpreset
archives_base_name=jumpreset
